[package]
name ="test_rust"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = "debuginfo"

[profile.dev.package."*"]
opt-level = 3


[dependencies.windows]
version = "0.48"
features = [
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Graphics",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]
[dependencies]
opencv = "0.82.1"
pyo3 = "0.19.0"
winapi = { version = "0.3.9", features = ["winuser","libloaderapi","shellapi","winerror","dwmapi","shellscalingapi"] }
# windows = {version = "0.48.0",features = ["win32"] }
# opencv = {version = "*", features = ["buildtime-bindgen"]}

# mnist = {version = "0.5.0",features = ["download"]}
ndarray = "*"
anyhow       = "1"

image = "0.24.6"
show-image = "0.13.1"
screenshots = "0.6.0"
